<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Kalai" failures="2" tests="2" name="Test(failed)" time="0.008" errors="0" timestamp="2023-08-12T15:14:49 IST">
  <testcase classname="org.testFail.ClassA" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testFail.ClassA.test2(ClassA.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testFail.RunfailTest.runfail(RunfailTest.java:25)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="org.testFail.ClassA" name="test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testFail.ClassA.test1(ClassA.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testFail.RunfailTest.runfail(RunfailTest.java:25)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed) -->
